version: '3.5'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - postgres
    restart: unless-stopped
  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=postgres
      - DB_NAME=$POSTGRES_DB
      - POOL_MODE=transaction
      - ADMIN_USERS=postgres,$POSTGRES_USER
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=0
    ports:
      - "5432:5432"
    networks:
      - postgres
    depends_on:
      - postgres
networks:
  postgres:
    driver: bridge

